[package]
name = 'bingo'
version = '1.0.0'

[dependencies.AptosFramework]
subdir = 'aptos-move/framework/aptos-framework'
rev = 'aptos-release-v1.4'
git = 'https://github.com/aptos-labs/aptos-core.git'

[addresses]
admin = "0x1337"
overmind = "0x1337"